version: 2
updates:
  - package-ecosystem: "maven" # Specify the package ecosystem as Maven
    directory: "/" # Location of the package manifests (root directory)
    schedule:
      interval: "weekly"
